---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
   app: myapp
   type front-end
spec:
  containers:
   - name: mynginx-container
     image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: myservice
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
 selector:
    type: front-end