apiVersion: v1
kind: PersistentVolume
metadata:
        name: myvolume
spec:
  accessModes:
          - ReadWriteOnce
  capacity:
          storage: 1Gi
  hostPath:
       path: "/tmp/data"
~                      