apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
       - mountPath: "/var/www/html"
         name: web
  volumes:
    - name: web
      persistentVolumeClaim:
        claimName: myclaim