---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    app: myapp
    type: front-end
spec:
 containers:
  - name: mynginx-container
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: myservicce
spec:
  selector:
    type: front-end
  type: NodePort
  ports:
   - name: http
     protocol: tcp
     port: 80
     targetPort: 80
     nodePort: 30000
